In [19]:
import numpy as np
aarray=np.array([[0,1],[2,3],[4,5]])
barray=np.array([[0,1,2,3],[4,5,6,7]])
c=np.dot(aarray,barray)
print(c)
np.sum(c)

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


np.int64(234)